# Documentation: https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: all

  settings:
    tagliatelle:
      case:
        rules:
          json: snake

    varnamelen:
      ignore-names:
        - err
        - ok

    wsl:
      allow-cuddle-declarations: true

  disable:
    - depguard # Allow non whitelisted package imports
    - err113 # Allow dynamic errors (fmt.ErrorF("..."))
    - forbidigo # Allow print statements
    - godox
    - mnd
    - revive
    - whitespace
